[package]
name = "langid"
version = "0.0.1"
authors = ["Aleksei Voronov <despawn@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
rustc-serialize = "0.3.18"
itertools = "0.4.11"
getopts = "0.2.14"

[dev-dependencies]
glob = "0.2.11"
